# Generated by Django 5.0.4 on 2024-04-15 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_subjects_alter_news_categories_news_subjects"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="Pictures",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="reply",
        ),
        migrations.AlterField(
            model_name="comment",
            name="news",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_news",
                to="news.news",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="comment_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
