# Generated by Django 5.0.4 on 2024-04-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pictures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="images/")),
                ("descriptions", models.CharField(max_length=180)),
            ],
            options={
                "verbose_name": "pictures",
                "verbose_name_plural": "Pictures",
            },
        ),
        migrations.CreateModel(
            name="YouTubeVideoUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField()),
                ("title", models.CharField(max_length=80)),
                ("descriptions", models.CharField(max_length=300)),
            ],
            options={
                "verbose_name": "youtube_video",
                "verbose_name_plural": "YouTube Videos",
            },
        ),
    ]
