# Generated by Django 5.0.3 on 2024-04-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='descriptions',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideourl',
            name='descriptions',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
