# Generated by Django 5.0.3 on 2024-04-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_alter_pictures_descriptions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonimusUserEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'anonimus_user_emails',
                'verbose_name_plural': 'Anonimus User Emails',
            },
        ),
    ]
