# Generated by Django 5.0.4 on 2024-04-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='users/images/default/avatar.jpeg', null=True, upload_to='users/images/'),
        ),
    ]
